### ISSUE TITLE
isssue with underwater caves

### ISSUE THREAD

**Issue by Scapulaunit12** [Melonslise/Subterranean-Wilderness#1]
Hey this mod is beautiful from what I have experienced so far, but there seems to be a glitch in underwater caves where coral floates with no rocks attached to it. 

If this helps I do have yung's better caves installed.
![water](https://user-images.githubusercontent.com/56084328/96376501-37b9a780-114d-11eb-8c10-5478b9768c62.JPG)

**Comment by PaintNinja** [comment]
Hello, to help us debug this, please provide us with the following:
- World seed
- Coords
- List of installed mods

Installing BLAME will also help identify problematic mods that could be breaking worldgen for everyone, you can get it here: https://www.curseforge.com/minecraft/mc-mods/blame

If you have Optifine installed, you need version OptiFine HD U **G4 pre2** or newer as older versions will break worldgen in strange and subtle ways.

**Comment by NovaNeon4** [comment]
This issue is happening for me as well, and I also have YUNG's better caves installed. I'm assuming that's the cause of the error, I'll be testing out a world generated without it in a bit.

**Comment by Scapulaunit12** [comment]
seed:-6469536112119306917
cords:-99.115/31.48659/244.091

The mods I have installed are these:
![mods installed](https://user-images.githubusercontent.com/56084328/96376995-3342be00-1150-11eb-9f8d-575e940cbfc4.JPG)

Also I tested this in a world without Yungs and didnt have this issue. Im pretty sure its a problem with yungs.

**Comment by NovaNeon4** [comment]
Confirming, I have virtually every other 1.16.3 mod installed possible (currently at 209 mods) and the issue only happens when I have YUNG's better caves installed. This bug is caused by an incompatibility between YUNG's and this mod.

**Comment by PaintNinja** [comment]
Anything showing up in the logs from BLAME on game load, world join, worldgen, world save or game quit?

**Comment by NovaNeon4** [comment]
Let me reinstall YUNG's and generate a new world, it'll be about 10-15 mins.

**Comment by Melonslise** [comment]
I believe this is a compat issue with Yung's better caves. I've already had multiple users report this issue. I'll try to work on a fix later

**Comment by NovaNeon4** [comment]
Alright, here's my **latest.log** as well as a screenshot including the world seed and coordinates of the bug. Replicated by generating a new world with YUNG's better caves and Subterranean Wilderness and simply going into spectator mode / flying underground.
[latest.log](https://github.com/Melonslise/Subterranean-Wilderness/files/5398033/latest.log)
![2020-10-18_12 09 49](https://user-images.githubusercontent.com/43053729/96377597-7d6d7480-113b-11eb-9815-fc96164c8576.png)

**Comment by PaintNinja** [comment]
Confirmed here in a clean Forge instance with just SubWild + Yung's caves + Blame.

**Comment by yungnickyoung** [comment]
Do the vines and whatnot only generate improperly along chunk boundaries? If so, you can try only generating them from x/z = 1 to 14 within a chunk, instead of 0 to 15.

**Comment by Scapulaunit12** [comment]
Yep I they only generate on chunk borders, I 
![1](https://user-images.githubusercontent.com/56084328/96941577-c5c0c580-14a0-11eb-9e87-0d8f8f9069d7.JPG)
![2](https://user-images.githubusercontent.com/56084328/96941579-c6595c00-14a0-11eb-95f7-147f7a37437b.JPG)
![3](https://user-images.githubusercontent.com/56084328/96941583-c6595c00-14a0-11eb-9a79-c9177a1da201.JPG)


just found out.

**Comment by NovaN4** [comment]
Issue no longer happens with most caves, but it still occurs in Ice caves. Ice and snow walls generate along chunk borders.

**Comment by yungnickyoung** [comment]
Should hopefully be fixed with Better Caves v1.1.
