### ISSUE TITLE
Crashing and infinite 100% loading

### ISSUE THREAD

**Issue by EbonyDream** [Melonslise/Subterranean-Wilderness#10]
So I've been trying to get this to work and I have found that I cannot create a world without the game crashing if I have optifine installed. Which is a shame cause Optifine is a near essential mod that i use to improve performance and get the most out of texture packs. I am using the latest version of Forge and Optifine. Even if they are the only two mods I have installed. 

If I remove Optifine and create a world it doesn't crash but so far I still haven't successfully managed to create a world with this mod, even if I make sure its the only mod installed, as it would be stuck creating the world. It would get stuck at a 100%. I have let it sit at 100% for about 10 minutes with no change. I have tried exiting out of the game and attempting to load the world again with no changes, despite waiting another 10 minutes.

**Comment by Melonslise** [comment]
What version?

**Comment by EbonyDream** [comment]
The Minecraft Version I'm playing on is 1.16.3 
The version of Optifine is 1.16.3 HD U G5
The Forge version is 1.16.3 34.1.42

**Comment by harmalom** [comment]
It is not optifine's problem, it is the mod that is incompatible with the new versions of forge, that's why it is not compatible with 1.16.4

**Comment by EbonyDream** [comment]
I'm not using or even playing on 1.16.4 though,

**Comment by harmalom** [comment]
what I mean is that the mod is compatible only until forge version 34.1.41, from then on it is not compatible with any forge version including 1.16.4

**Comment by EbonyDream** [comment]
Ah I see, well that's kind of silly cause other mods I use require the latest version so that sucks. I guess I'll either have to wait for the mod to be updated or to find a work around or something or just not use the mod at all.

**Comment by PaintNinja** [comment]
It's not an artificial restriction, it's a bug. It'll probably be fixed when it's updated to 1.16.4.
