### ISSUE TITLE
Worldgen Crash

### ISSUE THREAD

**Issue by TechniumUnlimited** [Melonslise/Subterranean-Wilderness#14]
https://pastebin.com/fpa5SqC8

**Comment by NovaN4** [comment]
Incompatibility with Terraforged on this mod's end, I was literally just about to report this.

**Comment by TechniumUnlimited** [comment]
Thanks for letting me know

**Comment by NovaN4** [comment]
Nothing to do with Terraforged actually... I just removed Terraforged and got this crash again. It's entirely this mod's side. Also, yeah, as shown by Mickelus this happens without Terraforged but with Tetra.

**Comment by WenXin20** [comment]
Hello, I also got this crash, but I do not have terraforged or tetra installed. It seems to be crashing with enhanced vanilla or overworld two. [Crash Log](https://gist.github.com/WenXin20/b7e9d7313303f00dff2404d43e55316e)

**Comment by thedeerirty** [comment]
Believe this is Tetra and Eidolon can also cause this. Hope this is fixed soon, I'd love to use this mod again
