### ISSUE TITLE
No footstep sounds on piles

### ISSUE THREAD

**Issue by NovaN4** [Melonslise/Subterranean-Wilderness#15]
Steps to reproduce:
1. Go to any pile of gravel, dirt, etc added by this mod
2. Walk on it
3. No sound comes out like usual when walking

**Comment by Corvus20** [comment]
I was going to mention this too. It feels really weird walking in a desert cave with the footstep sounds going on and off.

**Comment by Guy-IV** [comment]
I think it's fixed, it was a bug with dynamic surroundings and the patch came out a day ago!

**Comment by MrKashew** [comment]
Still getting this problem

**Comment by NovaN4** [comment]
#26
