### ISSUE TITLE
Crash while exploring [1.16]

### ISSUE THREAD

**Issue by mr-poyo** [Melonslise/Subterranean-Wilderness#18]
Hello,

I am working on a vivecraft modpack and think this mod would be a great addition for immersion. Not sure, but I think I might be getting a crash on world-gen. I don't use terraforge as I saw in another issue. Thank you!

Crash report: https://pastebin.com/KELFrfs2
SubWild-1.16.4-1.1.1.jar

**Comment by TelepathicGrunt** [comment]
It seems this cast issue occurred here where the IWorld isnt a world. It should stay an IWorld instead.
<https://github.com/Melonslise/Subterranean-Wilderness/blob/3f5a03f31e59fa7d7748c30ad40d3de4d348a90f/src/main/java/melonslise/subwild/common/block/SpeleothemBlock.java#L100> 

But looking at how vanilla does their falling blocks, they seem to schedule a tick and then the next tick in scheduledTick is when they make the falling block entity. Which makes sense as scheduledTick has the correct world needed to spawn an entity. If you really do not want to schedule ticks, then you can try `IServerWorld.func_242417_l` instead as that's the method nbt structures use to spawn entities safely during worldgen.

**Comment by Melonslise** [comment]
@TelepathicGrunt Thank you! Uploading fix now..
