### ISSUE TITLE
Walking on certain blocks produces no sound

### ISSUE THREAD

**Issue by KyleLord** [Melonslise/Subterranean-Wilderness#20]
Walking on patches or through puddles don't make a sound associated with that block. No splashes through puddles or crunches on gravel patches for example. You'll hear the "walking on stone" sound effect on stone blocks and then step on what appears to be stone but hear nothing. This is especially apparent when Dynamic Surroundings is installed.

**Comment by PaintNinja** [comment]
Thank you for reporting, this should be fixed in v1.3.1. If you still have this issue on v1.3.1, please leave a comment here and I'll reopen this.
