### ISSUE TITLE
Remove if your not updating.

### ISSUE THREAD

**Issue by MagmaBro123** [Melonslise/Subterranean-Wilderness#27]

**Comment by xemnes** [comment]
do you seriously still go round claiming mods that dont get updated should be removed? how many times must you be told before you understand this.

**Comment by PaintNinja** [comment]
People get busy and have other things in their lives to sort out. Unless you're willing to write a contract guaranteeing that you'll pay someone a full-time salary for maintaining a mod, don't expect consistently quick updates.
