### ISSUE TITLE
worldgen crash with tetra

### ISSUE THREAD

**Issue by lag42** [Melonslise/Subterranean-Wilderness#3]
tetra's structures only spawn in cold biomes and even then this crash is not guranteed making it not entirely consistent to reproduce, but it does seem to happen and i managed to do it in a clean instance with:

subwild: 1.16.3-1.0
tetra: 1.16.3-3.1.0
mgui: 1.16.3-3.1.2

[crash report](https://gist.github.com/lag42/94396eae3017bdda1a3a9145d20668e3)

**Comment by Corvus20** [comment]
I am having this same issue. My crash reports mention "tetra:feature" and SubWild's spleleotherms. The thread about eidolon might be discussing an issue with the same cause.
