### ISSUE TITLE
Tetra incompatibility/Crash

### ISSUE THREAD

**Issue by bryinabrt** [Melonslise/Subterranean-Wilderness#30]
Game crashes when it tries to load Tetra's underground ancient ruins in taiga biomes. At first I thought it was a Tetra bug, however once I removed Subterranean Wilderness it was working as intended.

Log is here: https://paste.ee/p/c9LHw

**Comment by PaintNinja** [comment]
Thanks for your report, it seems like you're using an outdated version of SubWild, I believe this was fixed in v1.2.2.

https://stopmodreposts.org
https://stopmodreposts.org/extension.html
