### ISSUE TITLE
[Bug] Visual glitch on Molten Stone while using shaders

### ISSUE THREAD

**Issue by arBorghi** [Melonslise/Subterranean-Wilderness#32]
Well, it's just a small glitch but it kinda destroys the atmosphere that this mod brings.
I opened a issue at OptiFine's GitHub and they said that it's because the vertex data was writen as fixed or somethin like that.

Here's the link: https://github.com/sp614x/optifine/issues/5448
![image](https://user-images.githubusercontent.com/63486777/111519160-92275600-8735-11eb-89b8-0a0fa96d16af.png)

**Comment by PaintNinja** [comment]
Thanks for your report and checking with the Optifine dev first. I've implemented spx614x's suggestion and tested the before and after and can confirm it's now fixed.

The fix'll be out in the next version of SubWild. In the meantime, you can use Optifine G7 as a temporary workaround.
