### ISSUE TITLE
Infinite lava source problem

### ISSUE THREAD

**Issue by Viitox666** [Melonslise/Subterranean-Wilderness#35]
Hey! I was testing some features of this lovely mod and I found something that I personally think should not be in it, an infinite lava source.
So the issue comes with breaking a molten core block, wich creates a lava source  on the block location and after that it breaks and drops itself making it possible to generate infinite lava sources, just break the block, bucket the lava and put the block back and repeat.
This is not a huge problem, but I though I should register it just in case.
Keep up the good work, and thanks for the config update it is very handy!

**Comment by PaintNinja** [comment]
Thanks for your report and feedback! This issue has been fixed by #42 and will be in the next update.
