### ISSUE TITLE
The texture of Molten Blackstone and Foxfire Mushrooms are messed up

### ISSUE THREAD

**Issue by elliothawkz2** [Melonslise/Subterranean-Wilderness#36]

**Comment by elliothawkz2** [comment]
Here's a screenshot of the issue
![2021-04-02_18 56 49](https://user-images.githubusercontent.com/68361341/113468697-02421580-9472-11eb-99b4-d74435475463.png)

**Comment by PaintNinja** [comment]
Updating SubWild to v1.2.0 should fix the issue. If it doesn't, please leave another comment on this issue and I'll reopen it.

https://stopmodreposts.org
https://stopmodreposts.org/extension.html
