### ISSUE TITLE
[Suggestion] Molten block improvements

### ISSUE THREAD

**Issue by MarioSMB** [Melonslise/Subterranean-Wilderness#40]
The molten blocks are great, they add much-needed variation to the lower levels of the cave system and a fun little trap to watch out for. However, there's a few things that seem odd about them that I believe could be improved by the following suggestions:  

- When broken, have the molten blocks drop their regular block form (e.g. molten stone would drop cobblestone along with the lava, molten andesite would drop regular andesite etc). This would prevent the blocks from being recycled and producing infinite lava (or obsidian when in water where it's easier to recollect the item)
- With Tinker's Construct installed, allow casting 1 bucket of lava into blocks to obtain their molten variant
- Don't allow using molten variants in place of their regular blocks in crafting recipes. This solves a few issues, especially if the above suggestions are considered
- With Create installed, allow washing molten blocks to obtain obsidian, matching Create's magma block washing recipe
- Hurt players who walk on molten blocks. This is mostly a consistency suggestion; it's very difficult and confusing to tell in a cave if the similar-looking block is going to hurt or not (they blend well with magma blocks!)
- Don't produce lava if the block is mined with silk touch. The molten block would be collected instead of its regular form this way, allowing them to be safely obtained

I hope these changes can be considered, thank you.

**Comment by PaintNinja** [comment]
All suggestions implemented. Thanks for your help and feedback! :)
