### ISSUE TITLE
[Bug Report] New blocks aren't affected by the Efficiency enchantment

### ISSUE THREAD

**Issue by coderepo8593** [Melonslise/Subterranean-Wilderness#46]
I noticed this bug when I was mining dirt. Almost every block would be instantly mined except for dirt stairs and dirt slab. For whatever reason, the Efficiency enchantment isn't being taken into account when mining the new dirt variants.

I haven't tested with blocks like the hot diorite or other pickaxe related blocks. I do know for sure it is an issue with this mod as Jade gives the info stating the block is from this mod. I was playing this originally in a modpack called Mineshafts and Monsters, so I wasn't sure if it was some kind of incompatibility or this mod itself. To rule that out, I loaded up a test environment with a basic list of minimal mods and this one. It happens in the test environment as well. So it isn't some kind of incompatibility with other mods causing it. It happens by this mod alone.

**Comment by NebelFox** [comment]
I have a similar problem. But in my case the new dirt blocks (noticed with dirt slabs and stairs currently) doesn't care about the tool I'm using to break them. Thus, breaking speed is the same for hand and a showel.

**Comment by PaintNinja** [comment]
Thank you for reporting, this has been fixed in the next update (v1.3.1)
